name: odsc_workshop
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - jupyter
  - ipykernel
  - scikit-learn
  - nltk